// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlIaR1Y2oDvh6AHbjKVoBbx_tIx7sp4Qo',
    appId: '1:622866899821:web:1ef03520929bc50772b064',
    messagingSenderId: '622866899821',
    projectId: 'coupons-f3570',
    authDomain: 'coupons-f3570.firebaseapp.com',
    storageBucket: 'coupons-f3570.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBFM8jNHhfaJHaD7-6yfzFDGjq1ANNnFU',
    appId: '1:622866899821:android:2ab56a06eec646ac72b064',
    messagingSenderId: '622866899821',
    projectId: 'coupons-f3570',
    storageBucket: 'coupons-f3570.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGhcfadOCsz6xWjUXmQci96vxLguHqkYU',
    appId: '1:622866899821:ios:a6a7568a18b0962772b064',
    messagingSenderId: '622866899821',
    projectId: 'coupons-f3570',
    storageBucket: 'coupons-f3570.appspot.com',
    iosBundleId: 'com.example.coupons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGhcfadOCsz6xWjUXmQci96vxLguHqkYU',
    appId: '1:622866899821:ios:1e6beae86c8c917a72b064',
    messagingSenderId: '622866899821',
    projectId: 'coupons-f3570',
    storageBucket: 'coupons-f3570.appspot.com',
    iosBundleId: 'com.example.coupons.RunnerTests',
  );
}
